name = "irontrack-preview"
compatibility_date = "2024-01-01"

[build]
command = "pnpm install && pnpm build"
cwd = "standalone-v2"

[build.upload]
format = "service-worker"
dir = "standalone-v2/dist"

[[pages_build_output_dir]]
value = "standalone-v2/dist"
